global:
  scrape_interval:     5s # default 15s
  evaluation_interval: 5s # default 15s

scrape_configs:
  - job_name: 'prometheus'

    scrape_interval: 100ms

    static_configs:
         - targets: ['localhost:9090']

  - job_name: 'cadvisor'

    scrape_interval: 100ms

    static_configs:
         - targets: ['cadvisor:8080']

  - job_name: 'node-exporter'

    scrape_interval: 100ms

    static_configs:
         - targets: ['node-exporter:9100']

  - job_name: 'qdrant'

    scrape_interval: 100ms

    static_configs:
         - targets: ['qdrant:6333']